import Head from 'next/head'
import Image from 'next/image'
import Banner from '@/components/Banner'
import Card from '@/components/Card'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import coffeeStores from '../data/coffee-stores.json'

const inter = Inter({ subsets: ['latin'] })

export async function getStaticProps(context) {
  console.log('hi getStaticProps')

  const options = {
    method: 'GET',
    headers: {
      accept: 'application/json',
      Authorization: process.env.FOURSQUARE_API_KEY,
    },
  }

  const response = await fetch(
    'https://api.foursquare.com/v3/places/search?query=coffee&ll=43.6652050140595%2C-79.39708299370781&limit=6',
    options
  )
  const data = await response.json()
  // .then(response => response.json())
  // .then(response => console.log(response))
  // .catch(err => console.error(err))

  return {
    props: {
      coffeeStores: data.results,
    },
  }
}

export default function Home(props) {
  console.log('props', props)
  const handleOnBannerBtnClick = () => {
    console.log('hi banner button')
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Coffee Connoisseur</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Banner buttonText="View Stores Nearby" handleOnClick={handleOnBannerBtnClick} />
        <div className={styles.heroImage}>
          <Image src="/static/hero-image.png" width={700} height={400} alt="Hero Image" />
        </div>
        {props.coffeeStores.length > 0 && (
          <>
            <h2 className={styles.heading2}>Toronto Stores</h2>
            <div className={styles.cardLayout}>
              {props.coffeeStores.map(coffeeStore => (
                <Card
                  key={coffeeStore.fsq_id}
                  name={coffeeStore.name}
                  imgUrl={
                    coffeeStore.imgUrl ||
                    'https://images.unsplash.com/photo-1504753793650-d4a2b783c15e?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=2000&q=80'
                  }
                  href={`/coffee-store/${coffeeStore.fsq_id}`}
                />
              ))}
            </div>
          </>
        )}
      </main>
      <footer></footer>
    </div>
  )
}
